#!/bin/sh

set -e
. /usr/share/debconf/confmodule

CONFIGFILE=/etc/freenetis/freenetis-ssh-keys.conf

# Load config file, if it exists.
if [ -e $CONFIGFILE ]; then
	db_get freenetis-ssh-keys/hack_reload
	if [ "$RET" = true ]; then
		. $CONFIGFILE || true
		db_set freenetis-ssh-keys/path_freenetis "$PATH_FN"
		db_set freenetis-ssh-keys/device_id "$DEVICE_ID"
	fi
fi

# h@ck for not reloading variables from config file (enabled again by postinst)
db_set freenetis-ssh-keys/hack_reload false

# Ask questions.
db_input critical freenetis-ssh-keys/path_freenetis || true
db_input critical freenetis-ssh-keys/device_id || true
db_go || true