#!/bin/sh
# FreenetIS-redirection DEB: actions before uninstalling of package

set -e
. /usr/share/debconf/confmodule

NAME=freenetis-redirection
CONFIGFILE=/etc/freenetis/freenetis-redirection.conf

# disable startup from update-rc.d
update-rc.d -f ${NAME} remove

# remove all configuration if purge
if [ "$1" = purge ]; then
	# remove defconf values
	if [ -e /usr/share/debconf/confmodule ]; then
		db_purge
	fi
	# remove config files
	rm -f $CONFIGFILE
	# remove dir if empty
	[ "$(ls -A /etc/freenetis)" ] || rm -rf /etc/freenetis
fi

#DEBHELPER#
