<?php defined('SYSPATH') or die('No direct access allowed.');
/*
 * This file is part of open source system FreenetIS
 * and it is released under GPLv3 licence.
 * 
 * More info about licence can be found:
 * http://www.gnu.org/licenses/gpl-3.0.html
 * 
 * More info about project can be found:
 * http://www.freenetis.org/
 * 
 */

$lang = array
(
	'welcome_subject' => 'Welcome in Freenetis',
	'welcome' => "Freenetis is informatice system for evidence of your pays.<br /> More info can be found at <a href='http://www.freenetis.org' target='_blank'>http://www.freenetis.org</a>.<br /><br />Please don not react on this message, it was automatically generated by system.",

	'your_work_add_subject' => 'Your work has been added',
	'your_work_add' => "Your work was added to the system by user <b>%s</b>. Check the state of voting or view work you can <b><a href='%s'>here</a></b>.<br /><br />Please don not react on this message, it was automatically generated by system.",
	'your_work_update_subject' => 'Your work has been updated',
	'your_work_update' => "Your work was updated by user <b>%s</b>. Check the state of voting or view work you can <b><a href='%s'>here</a></b>.<br /><br />Please don not react on this message, it was automatically generated by system.",
	'your_work_delete_subject' => 'Your work has been deleted',
	'your_work_delete' => "Your work with text %s was deleted by user <b>%s</b>.<br /><br />Please don not react on this message, it was automatically generated by system.",

	'your_work_vote_add_subject' => "Vote to your work has been added",
	'your_work_vote_add' => "User <b>%s</b> added vote to your work. Check the state of voting or view work you can <b><a href='%s'>here</a></b>.<br /><br /> Please don not react on this message, it was automatically generated by system.",
	'your_work_approve_subject' => "Your work has been approved",
	'your_work_approve' => "User <b>%s</b> added vote to your work and your work has been approved. View work you can <b><a href='%s'>here</a></b>.<br /><br /> Please don not react on this message, it was automatically generated by system.",
	'your_work_reject_subject' => "Your work has been rejected",
	'your_work_reject' => "User <b>%s</b> added vote to your work and your work has been rejected. View work you can <b><a href='%s'>here</a></b>.<br /><br /> Please don not react on this message, it was automatically generated by system.",

	'work_add_subject' => 'Work has been added',
	'work_add' => "User work was added to the system <b>%s</b>. Vote or view work you can <b><a href='%s'>here</a></b>.<br /><br />Please don not react on this message, it was automatically generated by system.",
	'work_update_subject' => 'Work has been updated',
	'work_update' => "In the system was updated user work <b>%s</b>. Vote or view work you can <b><a href='%s'>here</a></b>.<br /><br />Please don not react on this message, it was automatically generated by system.",
	'work_delete_subject' => 'Work has been deleted',
	'work_delete' => "In the system was deleted user work <b>%s</b> with text %s.<br /><br />Please don not react on this message, it was automatically generated by system.",

	'work_vote_add_subject' => "Vote to work has been added",
	'work_vote_add' => "User <b>%s</b> added vote to work of user <b>%s</b>. Vote or view work you can <b><a href='%s'>here</a></b>.<br /><br /> Please don not react on this message, it was automatically generated by system.",
	'work_approve_subject' => "Work has been approved",
	'work_approve' => "User <b>%s</b> added vote to work of user <b>%s</b> and this work has been approved. View work you can <b><a href='%s'>here</a></b>.<br /><br /> Please don not react on this message, it was automatically generated by system.",
	'work_reject_subject' => "Work has been rejected",
	'work_reject' => "User <b>%s</b> added vote to work of user <b>%s</b> and this work has been rejected. View work you can <b><a href='%s'>here</a></b>.<br /><br /> Please don not react on this message, it was automatically generated by system.",

	'phone_invoice_warning_subject' => 'Phone invoice for number %s in period from %s to %s',
	'phone_invoice_warning' => "To the system was added phone invoice, which contains your phone number %s.<br /><br />In interface <a href='%s'><b>My phone invoices</b></a> please fill, which phone calls and services was private and which company.",
);
